name: CI - Trello API Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:   

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Trello API tests
        run: npm run test:trello:ci
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: trello-api-report
          path: ./newman/trello-report.html
